name: Despliegue Automatico Node Org

on:
  push:
    branches:
      - main

jobs:
  desplegar:
    runs-on: self-hosted

    steps:
      - name: Descargar cambios de GitHub con pase VIP
        run: |
          cd /home/serverst-01/serverst-01
          git pull https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/lab-capibaras/NodeServer.git main --no-edit
          
      - name: Reconstruir y reiniciar contenedor de Node
        run: |
          cd /home/serverst-01/serverst-01
          sudo docker compose down
          sudo docker compose up -d --build